# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37dfe7698b5e4b2358ac36bdf532a4c5e022618a549e6fd4b8d7b8635ca4b61f94f3c6688b9f09e5fa37b00a7f67cd04e7afd90051cf1a49be5d83316611ac5d

test:
  secret_key_base: ea4b88d97c83eb0b5849d05748faf512228dc31763ff6440f099d0760c6c67b05ec8cc7983403af7e76ccaf5efa5b8242973037d67c92304d75a67e68cadc355

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
